version: '2.2'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - /Users/saiprashaanth/Desktop/code/thingsboard/mytb-data:/data
      - /Users/saiprashaanth/Desktop/code/thingsboard/mytb-logs:/var/log/thingsboard
